### PR TITLE
Conversion of simplex to WASM

### LINKED ISSUE #74: create wasm noise
We currently have a js implementation of simplex, but it is not very fast.

https://github.com/dojoengine/dojo.js/blob/main/packages/utils/src/game/simplex.ts

This task is to convert this into WASM, which will be significantly faster.

FYI - this pairs with the onchain simplex noise in the cubit cairo lib.

### PR DESCRIPTION
**Pull request by julienbrs**
Closes #74 

## Introduced changes

- Rewriting `simplex.ts` in rust to compile it to WASM and increasing perf, by using `wasm-pack`.
- Writing tests to ensure rust values are the same as ts values from `simplex.ts`

## Checklist

-   [x] Linked relevant issue
-   [ ] Updated relevant documentation
-   [ ] Added relevant tests
-   [ ] Add a dedicated CI job for new examples
-   [x] Performed self-review of the code

### CODE REVIEW

**Comment by tarrencev** [comment]
nice progress! as far as testing, i ideally we can compare the outputs to the cairo version rather than ts

**Comment by julienbrs** [comment]
> nice progress! as far as testing, i ideally we can compare the outputs to the cairo version rather than ts

Okay, will replace ts expected values by cairo ones. I'm also waiting for an other PR to be merged so I can test the wasm function manually in an example

**Comment by ponderingdemocritus** [comment]
PR has been merged now!

Please complete an example using this so we can merge!

**Comment by julienbrs** [comment]
> PR has been merged now!
> 
> Please complete an example using this so we can merge!

Sorry for the delay, lot of stuff going on IRL
React-phaser-example is now using the wasm version of `snoise` to generate the map. I wasn't able to launch the full example of react-phaser (with or without the wasm integration), but the map generation is working fine and that's what we want here, so I guess it's fine?

**Comment by ponderingdemocritus** [comment]
Thank you! Yes, i can finish it off

**Pull request merged**
