### PR TITLE
Update to dojo 0.4.5ish

### PR DESCRIPTION
**Pull request by broody**
Dependent on this PR: https://github.com/dojoengine/dojo/pull/1339

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
finished in #99

**Comment by ponderingdemocritus** [comment]
Having issues building 0.4.4

```rust
error: JSON open file crates/dojo-world/src/contracts/abi/world.json error: No such file or directory (os error 2)
  --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/world.rs:18:9
   |
18 |         abigen!(WorldContract, "crates/dojo-world/src/contracts/abi/world.json");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error: JSON open file crates/dojo-world/src/contracts/abi/executor.json error: No such file or directory (os error 2)
  --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/world.rs:23:9
   |
23 |         abigen!(ExecutorContract, "crates/dojo-world/src/contracts/abi/executor.json");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `crate::contracts::WorldContractReader`
  --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:17:5
   |
17 | use crate::contracts::WorldContractReader;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `WorldContractReader` in `contracts`

error[E0432]: unresolved imports `abigen::world::WorldContract`, `abigen::world::WorldContractReader`
 --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/world.rs:3:25
  |
3 | pub use abigen::world::{WorldContract, WorldContractReader};
  |                         ^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^ no `WorldContractReader` in `contracts::world::abigen::world`
  |                         |
  |                         no `WorldContract` in `contracts::world::abigen::world`

error[E0433]: failed to resolve: could not find `ExecutorContractReader` in `executor`
  --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/world.rs:62:31
   |
62 |             abigen::executor::ExecutorContractReader::new(executor_address.into(), &self.provider);
   |                               ^^^^^^^^^^^^^^^^^^^^^^ could not find `ExecutorContractReader` in `executor`

error[E0283]: type annotations needed
   --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:120:31
    |
120 |         let raw_values = self.entity_storage(keys).await?;
    |                               ^^^^^^^^^^^^^^ cannot infer type for type parameter `P`
    |
    = note: cannot satisfy `_: starknet::providers::Provider`
    = help: the following types implement trait `starknet::providers::Provider`:
              Box<U>
              SequencerGatewayProvider
              JsonRpcClient<T>
              Arc<U>
              AnyProvider
              &'a U
note: required by a bound in `ModelRPCReader::<'a, P>::entity_storage`
   --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:69:8
    |
69  |     P: Provider + Sync + Send,
    |        ^^^^^^^^ required by this bound in `ModelRPCReader::<'a, P>::entity_storage`
...
88  |     pub async fn entity_storage(
    |                  -------------- required by a bound in this associated function

error[E0277]: the size for values of type `[FieldElement]` cannot be known at compilation time
   --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:144:13
    |
144 |         let res = self.world_reader.executor_call(self.class_hash, entrypoint, vec![]).await?;
    |             ^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[FieldElement]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[FieldElement]` cannot be known at compilation time
   --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:144:19
    |
144 |         let res = self.world_reader.executor_call(self.class_hash, entrypoint, vec![]).await?;
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[FieldElement]`
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[FieldElement]` cannot be known at compilation time
   --> /Users/os/.cargo/git/checkouts/dojo-10cac2e09298cf35/8afd8c9/crates/dojo-world/src/contracts/model.rs:144:93
    |
144 |         let res = self.world_reader.executor_call(self.class_hash, entrypoint, vec![]).await?;
    |                                                                                             ^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[FieldElement]`
note: required by a bound in `Break`
   --> /rustc/87e1447aadaa2899ff6ccabe1fa669eb50fb60a1/library/core/src/ops/control_flow.rs:93:5
   ```

**Comment by ponderingdemocritus** [comment]
@glihm @broody

**Comment by broody** [comment]
@ponderingdemocritus it needs the abigen changes from glihm but we decided to hold off bumping dojo rev due to some starkli compatibility issues, fixing rev to that PR for now

**Pull request merged**
